# This is a config for E2B sandbox template.
# You can use template ID (w1d3maw07pkjh0h2qxro) or template name (vibe-web-builder) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("vibe-web-builder") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-web-builder") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-web-builder')

team_id = "e4969114-ad52-4187-b712-503773bf5661"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-web-builder"
template_id = "w1d3maw07pkjh0h2qxro"
